### ISSUE TITLE
Idea: Improve Syntax Highlighting

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/website-lingua-franca#70]
It appears that syntax highlighting for non-LF code is not supported. 
For example, there is no syntax highlighting for the following:
````
```bash
cd foo
```
````
But it could appear as
```bash
cd foo
```

**Comment by petervdonovan** [comment]
One way to do this is to include `vscode` as a submodule, and to reach into that repo for the desired `tmlanguage.json` file. The problem is that a deep clone of the whole repo and its history consumes 496 MiB!

We could find ways to manage that. For example, we could try to do only shallow clones, or we could keep the thing around and just tolerate it. We could also just copy-paste the `tmlanguage.json` files that we need, and update them manually as their maintainers work on them. As long as we can somehow track copies of those files, it shouldn't be a problem to highlight any code we want, including bash scripts.

I'm open to any opinions...

**Comment by Soroosh129** [comment]
> We could also just copy-paste the `tmlanguage.json` files that we need

Would it be possible to factor out the `tmlanguage.json` file to a third repository and have that as a submodule in the vscode and website repos?

**Comment by lhstrh** [comment]
...using a URL like this one: https://github.com/microsoft/vscode/blob/main/extensions/cpp/syntaxes/cpp.tmLanguage.json

**Comment by petervdonovan** [comment]
> Couldn't we just `wget` or `curl` those files?

Oh, I like that idea -- thanks! The way I can imagine implementing that would be to just get the text in the highlighting script, without needing to save anything to files. I'll go ahead and try to do that.
